#if !canImport(ObjectiveC)
import XCTest

extension AuthorizerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthorizerTests = [
        ("testAddRequestAuthorizer", testAddRequestAuthorizer),
        ("testAddRequestAuthorizerFailedKey", testAddRequestAuthorizerFailedKey),
        ("testAddRequestAuthorizerRequestExist", testAddRequestAuthorizerRequestExist),
        ("testAddRequestAuthorizerRequestInvalidSecret", testAddRequestAuthorizerRequestInvalidSecret),
        ("testAuthorizationResponse", testAuthorizationResponse),
        ("testParseRequest", testParseRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AuthorizerTests.__allTests__AuthorizerTests),
    ]
}
#endif
